/*
 * This source file was generated by the Gradle 'init' task
 */
package dio.bank;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAMain() {
        // Basic smoke test: Main class should be loadable
        assertNotNull(dio.bank.Main.class);
    }
}
